#!/usr/bin/env python3
"""Generate the Go launcher contract; --check is an offline release gate."""
import argparse
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def render():
    contract = json.loads((ROOT / "makewand" / "command_contract.json").read_text())
    if contract.get("schema") != 1:
        raise ValueError("unsupported command contract")
    delegated = set(contract["python_commands"]) - set(contract["native_go_commands"])
    lines = ["// Code generated by scripts/generate_cli_contract.py; DO NOT EDIT.", "package main", ""]
    for name, values in (("pythonOrchestratorCmds", delegated),
                         ("nativeGoCommands", contract["native_go_commands"]),
                         ("pythonGlobalValueFlags", contract["python_value_flags"]),
                         ("sharedGlobalValueFlags", contract["shared_value_flags"]),
                         ("pythonGlobalBooleanFlags", contract["python_boolean_flags"])):
        lines.append(f"var {name} = map[string]bool{{")
        lines.extend(f"\t{json.dumps(value)}: true," for value in sorted(values))
        lines.extend(["}", ""])
    return subprocess.run(["gofmt"], input="\n".join(lines), text=True,
                          capture_output=True, check=True).stdout


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = ROOT / "cmd" / "makewand" / "python_contract_generated.go"
    generated = render()
    if args.check:
        if not output.exists() or output.read_text() != generated:
            parser.exit(1, "Go command contract is stale; run python3 -I scripts/generate_cli_contract.py\n")
    else:
        output.write_text(generated, encoding="utf-8")


if __name__ == "__main__":
    main()
